const fs = require('fs');
const path = __dirname;
let map = JSON.parse(fs.readFileSync(`${path}/es-map.json`, 'utf8'));
let content = fs.readFileSync(`${path}/app.js`, 'utf8');
const sorted = Object.keys(map).filter(k => map[k] && map[k] !== k).sort((a, b) => b.length - a.length);
for (const k of sorted) content = content.split(k).join(map[k]);
content = content.replace(/ru-RU/g, 'es-ES');
content = content.replace(/new Intl\.DisplayNames\(\["ru"\]/g, 'new Intl.DisplayNames(["es"]');
content = content.replace(/localeCompare\(([^,]+),\s*"ru"\)/g, 'localeCompare($1, "es")');
fs.writeFileSync(`${path}/app.js`, content);
console.log('Applied', sorted.length, 'translations');
console.log('Cyrillic left:', (content.match(/[а-яА-ЯёЁ]/g) || []).length);
